import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";
import AppProvider from "../components/app-provider";
import { Inter, Roboto_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased `}>
        <AppProvider>
          <Toaster />

          {children}
        </AppProvider>
      </body>
    </html>
  );
}
